### PR TITLE
Changed Variable

### PR DESCRIPTION
**Pull request by guylamar2006**
Changed $OPENGAPPS_RELEASEDATE variable to automatically get system date so the gapps are recent.

### CODE REVIEW

**Comment by geeks-r-us** [comment]
Nice idea but my test today gave me the following URL: 
https://github.com/opengapps/x86_64/releases/download/20181218/open_gapps-x86_64-7.1-mini-20181218.zip
which ends in a file with a "Not Found" content

**Comment by iuridiniz** [comment]
I think you could use UTC dates (date -u)

**Comment by geeks-r-us** [comment]
The matter is  this script only works on date of release and not on the other days. 
simple hack is to count down days till it hits an existing file. But a look up would be better

**Comment by geeks-r-us** [comment]
done with d384d60

**Pull request closed without merging**
