### PR TITLE
Fix for issue #54 and #66

### PR DESCRIPTION
**Pull request by FoxieFlakey**
1. Users no longer need manually create the missing directory
2. Report the user when creating the missing directory

### CODE REVIEW

**Comment by Neurone** [comment]
Good fix for #54 (I'm writing here also to let GitHub cross-reference the PR with the issue)

**Comment by NickWilde263** [comment]
> Good fix for #54 and #66 (I'm writing here also to let GitHub cross-reference the PR with the issue)

good idea cross-reference is `#issueNumber` is how you reference issue

**Comment by NickWilde263** [comment]
Can anyone merge this

**Comment by geeks-r-us** [comment]
Done

Thx for your help

**Comment by FoxieFlakey** [comment]
you're welcome

**Pull request merged**
